name: Compile Jerasol OS Image

on:
  workflow_dispatch:

jobs:
  build-jerasol-os:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Jerasol Custom Repository Source
        uses: actions/checkout@v4

      - name: Maximize Disk Space and Allocate Virtual Memory Swap
        run: |
          echo "==> Clearing factory junk files..."
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/share/swift /usr/local/.ghcup
          sudo apt-get clean
          
          echo "==> Creating 12GB Memory Swap File to prevent out-of-RAM crashes..."
          sudo fallocate -l 12G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Install Essential Android Compiler Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev repo

      - name: Initialize Repo Source and Synchronize Files
        run: |
          git config --global user.email "developer@jerasol.com"
          git config --global user.name "Jerasol Developer"
          mkdir -p jerasol_workspace
          cd jerasol_workspace
          repo init -u https://github.com -b lineage-20.0 --depth=1 --git-lfs --no-tags
          repo sync -c -j2 --force-sync --no-clone-bundle --no-tags

      - name: Compile Custom Jerasol Framework Blocks
        run: |
          cd jerasol_workspace
          source build/envsetup.sh
          lunch aosp_arm64-userdebug
          
          # Throttling to 1 thread (-j1) to ensure the server never runs out of RAM
          mka bionic -j1
